name = 'image-api'
main = 'src/index.js'
compatibility_date = "2023-11-21"
node_compat = true
workers_dev = true
account_id =''


[vars]
AUTH_KEY_SECRET = ''
AWS_BUCKET_NAME='bucket'
AWS_BUCKET_REGION='us-west-2'
AWS_ACCESS_KEY=''
AWS_SECRET_ACCESS_KEY=''

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "bucket"
preview_bucket_name = "bucket-dev"
